# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171111_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_photo'),
        ),
    ]
