# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='photo',
        ),
        migrations.AddField(
            model_name='book',
            name='payment',
            field=models.CharField(default='payment', max_length=10),
        ),
    ]
