# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20171111_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payment',
            field=models.CharField(default='', max_length=10),
        ),
    ]
