# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20171111_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
