# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20171111_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
